<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AddUser.aspx.cs" Inherits="AddUser" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body bgcolor="#99ff66">
    <form id="form1" runat="server">
    <div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" CancelSelectOnNullParameter="False"
            ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:RFDBConnectionString %>"
            DeleteCommand="DELETE FROM [Operators] WHERE [Operator ID] = @original_Operator_ID AND [Password] = @original_Password AND [User Name] = @original_User_Name AND [Plant ID] = @original_Plant_ID AND [AccessProfile] = @original_AccessProfile"
            EnableCaching="True" EnableViewState="False" InsertCommand="INSERT INTO [Operators] ([Operator ID], [Password], [User Name], [Plant ID], [AccessProfile]) VALUES (@Operator_ID, @Password, @User_Name, @Plant_ID, @AccessProfile)"
            OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT [Operator ID] AS Operator_ID, [Password], [User Name] AS User_Name, [Plant ID] AS Plant_ID, [AccessProfile] FROM [Operators]"
            UpdateCommand="UPDATE [Operators] SET [Password] = @Password, [User Name] = @User_Name, [Plant ID] = @Plant_ID, [AccessProfile] = @AccessProfile WHERE [Operator ID] = @original_Operator_ID AND [Password] = @original_Password AND [User Name] = @original_User_Name AND [Plant ID] = @original_Plant_ID AND [AccessProfile] = @original_AccessProfile">
            <DeleteParameters>
                <asp:Parameter Name="original_Operator_ID" Type="String" />
                <asp:Parameter Name="original_Password" Type="String" />
                <asp:Parameter Name="original_User_Name" Type="String" />
                <asp:Parameter Name="original_Plant_ID" Type="String" />
                <asp:Parameter Name="original_AccessProfile" Type="String" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="User_Name" Type="String" />
                <asp:Parameter Name="Plant_ID" Type="String" />
                <asp:Parameter Name="AccessProfile" Type="String" />
                <asp:Parameter Name="original_Operator_ID" Type="String" />
                <asp:Parameter Name="original_Password" Type="String" />
                <asp:Parameter Name="original_User_Name" Type="String" />
                <asp:Parameter Name="original_Plant_ID" Type="String" />
                <asp:Parameter Name="original_AccessProfile" Type="String" />
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="Operator_ID" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="User_Name" Type="String" />
                <asp:Parameter Name="Plant_ID" Type="String" />
                <asp:Parameter Name="AccessProfile" Type="String" />
            </InsertParameters>
        </asp:SqlDataSource>
    
    </div>
        <asp:Button ID="btnOK" runat="server" PostBackUrl="~/Admin/UserAccounts.aspx" Style="z-index: 100;
            left: 362px; position: absolute; top: 291px" Text="Finished" Width="83px" OnClick="btnOK_Click" />
        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataSourceID="SqlDataSource1" Height="147px" Style="z-index: 102;
            left: 316px; position: absolute; top: 50px" Width="293px" AllowPaging="True" Caption="Add User" CaptionAlign="Top" DataMember="DefaultView" OnItemUpdated="DetailsView1_ItemUpdated" CellPadding="4" ForeColor="#333333" GridLines="None">
            <Fields>
                <asp:BoundField DataField="Operator_ID" HeaderText="Operator_ID" ReadOnly="True"
                    SortExpression="Operator_ID" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="User_Name" HeaderText="User_Name" SortExpression="User_Name" />
                <asp:BoundField DataField="Plant_ID" HeaderText="Plant_ID" SortExpression="Plant_ID" />
                <asp:BoundField DataField="AccessProfile" HeaderText="AccessProfile" SortExpression="AccessProfile" />
            </Fields>
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
            <EditRowStyle BackColor="#999999" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        </asp:DetailsView>
    </form>
</body>
</html>
